package com.example.expressiveapp.ui.theme

import androidx.compose.ui.graphics.Color

// Cores estáticas de fallback (usadas quando não há suporte a cor dinâmica)
val FallbackPrimary = Color(0xFF6750A4)
val FallbackOnPrimary = Color(0xFFFFFFFF)
val FallbackPrimaryContainer = Color(0xFFEADDFF)
val FallbackOnPrimaryContainer = Color(0xFF21005D)
val FallbackSecondary = Color(0xFF625B71)
val FallbackOnSecondary = Color(0xFFFFFFFF)
val FallbackSecondaryContainer = Color(0xFFE8DEF8)
val FallbackOnSecondaryContainer = Color(0xFF1D192B)
val FallbackTertiary = Color(0xFF7D5260)
val FallbackOnTertiary = Color(0xFFFFFFFF)
val FallbackTertiaryContainer = Color(0xFFFFD8E4)
val FallbackOnTertiaryContainer = Color(0xFF31111D)
val FallbackError = Color(0xFFB3261E)
val FallbackOnError = Color(0xFFFFFFFF)
val FallbackErrorContainer = Color(0xFFF9DEDC)
val FallbackOnErrorContainer = Color(0xFF410E0B)
val FallbackBackground = Color(0xFFFFFBFE)
val FallbackOnBackground = Color(0xFF1C1B1F)
val FallbackSurface = Color(0xFFFFFBFE)
val FallbackOnSurface = Color(0xFF1C1B1F)
val FallbackSurfaceVariant = Color(0xFFE7E0EC)
val FallbackOnSurfaceVariant = Color(0xFF49454F)
val FallbackOutline = Color(0xFF79747E)
val FallbackOutlineVariant = Color(0xFFCAC4D0)
val FallbackInverseSurface = Color(0xFF313033)
val FallbackInverseOnSurface = Color(0xFFF4EFF4)
val FallbackInversePrimary = Color(0xFFD0BCFF)
